import 'package:flutter/material.dart';

const classes = [
  {
    "number": 1,
    "level": "beginner",
    "image": "assets/home_screen/alphabets.png",
    "title": "First Steps in Berlin",
    "color": Color.fromARGB(255, 255, 184, 203),
    "subColor": Color.fromARGB(255, 202, 83, 115),
    "topics": [
      {
        "number": 0,
        "title": "Introduction",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 1,
        "title": "Greetings",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 2,
        "title": "Introducing Yourself",
        "image": "assets/home_screen/numbers.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 3,
        "title": "Asking Questions",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 4,
        "title": "Personal Pronouns",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 5,
        "title": "Basic Verbs",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 6,
        "title": "Definite and Indefinite Articles",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 6,
        "title": "Chapter Quiz",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ]
  },
  {
    "number": 2,
    "level": "beginner",
    "image": "assets/home_screen/list.png",
    "title": "Exploring the City",
    "color": Color.fromARGB(255, 197, 187, 245),
    "subColor": Color.fromARGB(255, 104, 95, 146),
    "topics": [
      {
        "number": 0,
        "title": "Introduction",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 1,
        "title": "Everyday Activities",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 2,
        "title": "Leisure Activities",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 3,
        "title": "Time Phrases",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 4,
        "title": "Days of the Week",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 5,
        "title": "Chapter Quiz",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ]
  },
  {
    "number": 3,
    "level": "beginner",
    "image": "assets/home_screen/list.png",
    "title": "Dining & Shopping",
    "color": Color.fromARGB(255, 137, 243, 144),
    "subColor": Color.fromARGB(255, 62, 169, 105),
    "topics": [
      {
        "number": 0,
        "title": "Introduction",
        "image": "assets/home_screen/list.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 1,
        "title": "Food & Drinks",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 2,
        "title": "Shopping Terms",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 3,
        "title": "Asking for Prices",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 4,
        "title": "Polite Requests",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 5,
        "title": "Numbers",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 6,
        "title": "Negation",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 7,
        "title": "Chapter Quiz",
        "image": "assets/home_screen/list.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ]
  },
  {
    "number": 4,
    "level": "beginner",
    "image": "assets/home_screen/alphabets.png",
    "title": "Daily Life in Germany",
    "color": Color.fromARGB(255, 255, 214, 102),
    "subColor": Color.fromARGB(255, 180, 134, 50),
    "topics": [
      {
        "number": 0,
        "title": "Introduction",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 1,
        "title": "Public Transport",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 2,
        "title": "Making Appointments",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 3,
        "title": "At the Post Office",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 4,
        "title": "Banking Basics",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 5,
        "title": "Asking for Help",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 6,
        "title": "Common Courtesies",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 7,
        "title": "Chapter Quiz",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ]
  },
  {
    "number": 5,
    "level": "beginner",
    "image": "assets/home_screen/alphabets.png",
    "title": "Social Interactions",
    "color": Color.fromARGB(255, 255, 153, 102),
    "subColor": Color.fromARGB(255, 180, 84, 50),
    "topics": [
      {
        "number": 0,
        "title": "Introduction",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 1,
        "title": "Making Friends",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 2,
        "title": "Phone Conversations",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 3,
        "title": "Social Media Communication",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 4,
        "title": "Giving Compliments",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 5,
        "title": "Discussing Hobbies",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 6,
        "title": "Handling Misunderstandings",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 7,
        "title": "Chapter Quiz",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ]
  },
  {
    "number": 6,
    "level": "intermediate",
    "image": "assets/home_screen/alphabets.png",
    "title": "Home & Family",
    "color": Color.fromARGB(255, 102, 204, 255),
    "subColor": Color.fromARGB(255, 50, 134, 180),
    "topics": [
      {
        "number": 0,
        "title": "Introduction",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 1,
        "title": "Household Items",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 2,
        "title": "Family Relationships",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 3,
        "title": "Renting an Apartment",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 4,
        "title": "Home Maintenance",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 5,
        "title": "Neighborhood Talk",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 6,
        "title": "German Home Traditions",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 6,
        "title": "Chapter Quiz",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ]
  },
  {
    "number": 7,
    "level": "intermediate",
    "image": "assets/home_screen/alphabets.png",
    "title": "German Culture",
    "color": Color.fromARGB(255, 204, 102, 255),
    "subColor": Color.fromARGB(255, 134, 50, 180),
    "topics": [
      {
        "number": 0,
        "title": "Introduction",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 1,
        "title": "Holidays & Celebrations",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 2,
        "title": "Dining Etiquette",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 3,
        "title": "Popular German TV",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 4,
        "title": "Understanding German Humor",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 5,
        "title": "Regional Differences",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 6,
        "title": "Cultural Do's and Don'ts",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 7,
        "title": "Chapter Quiz",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ]
  },
  {
    "number": 8,
    "level": "intermediate",
    "image": "assets/home_screen/alphabets.png",
    "title": "Work Life",
    "color": Color.fromARGB(255, 102, 255, 153),
    "subColor": Color.fromARGB(255, 50, 180, 100),
    "topics": [
      {
        "number": 0,
        "title": "Introduction",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 1,
        "title": "Job Interviews",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 2,
        "title": "Office Communication",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 3,
        "title": "Workplace Culture",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 4,
        "title": "Business Meetings",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 5,
        "title": "Work-Life Balance",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 6,
        "title": "German Work Benefits",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 7,
        "title": "Chapter Quiz",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ]
  },
  {
    "number": 9,
    "level": "intermediate",
    "image": "assets/home_screen/alphabets.png",
    "title": "Travel & Leisure",
    "color": Color.fromARGB(255, 255, 102, 204),
    "subColor": Color.fromARGB(255, 180, 50, 134),
    "topics": [
      {
        "number": 0,
        "title": "Introduction",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 1,
        "title": "Planning a Trip",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 2,
        "title": "At the Hotel",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 3,
        "title": "Sightseeing",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 4,
        "title": "Local Customs",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 5,
        "title": "Outdoor Activities",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 6,
        "title": "Travel Emergencies",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 7,
        "title": "Chapter Quiz",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ]
  },
  {
    "number": 10,
    "level": "intermediate",
    "image": "assets/home_screen/alphabets.png",
    "title": "Life Milestones",
    "color": Color.fromARGB(255, 223, 223, 0),
    "subColor": Color.fromARGB(255, 180, 180, 50),
    "topics": [
      {
        "number": 0,
        "title": "Introduction",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 1,
        "title": "Birth & Childhood",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 2,
        "title": "Education System",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 3,
        "title": "Weddings & Partnerships",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 4,
        "title": "Buying Property",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 5,
        "title": "Retirement Planning",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 6,
        "title": "German Life Events",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 7,
        "title": "Chapter Quiz",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ]
  },
  {
    "number": 11,
    "level": "advanced",
    "image": "assets/home_screen/alphabets.png",
    "title": "Community Life",
    "color": Color.fromARGB(255, 102, 255, 255),
    "subColor": Color.fromARGB(255, 50, 180, 180),
    "topics": [
      {
        "number": 0,
        "title": "Introduction",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 1,
        "title": "Local Government",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 2,
        "title": "Recycling & Sustainability",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 3,
        "title": "Community Events",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 4,
        "title": "Volunteering",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 5,
        "title": "Neighborhood Watch",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 6,
        "title": "German Clubs & Associations",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 7,
        "title": "Chapter Quiz",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ]
  },
  {
    "number": 12,
    "level": "advanced",
    "image": "assets/home_screen/alphabets.png",
    "title": "Media & Entertainment",
    "color": Color.fromARGB(255, 255, 153, 102),
    "subColor": Color.fromARGB(255, 180, 100, 50),
    "topics": [
      {
        "number": 0,
        "title": "Introduction",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 1,
        "title": "German Newspapers",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 2,
        "title": "Popular German Music",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 3,
        "title": "TV Shows & Movies",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 4,
        "title": "Book Culture",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 5,
        "title": "Sports Commentary",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 6,
        "title": "German Podcasts",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 7,
        "title": "Chapter Quiz",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ]
  },
  {
    "number": 13,
    "level": "advanced",
    "image": "assets/home_screen/alphabets.png",
    "title": "Food Culture",
    "color": Color.fromARGB(255, 204, 102, 255),
    "subColor": Color.fromARGB(255, 134, 50, 180),
    "topics": [
      {
        "number": 0,
        "title": "Introduction",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 1,
        "title": "Regional Cuisines",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 2,
        "title": "Cooking Terms",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 3,
        "title": "Dining Out",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 4,
        "title": "Food Shopping",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 5,
        "title": "German Baking",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 6,
        "title": "Food Festivals",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 7,
        "title": "Chapter Quiz",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ]
  },
  {
    "number": 14,
    "level": "advanced",
    "image": "assets/home_screen/alphabets.png",
    "title": "Everyday Technology",
    "color": Color.fromARGB(255, 255, 204, 102),
    "subColor": Color.fromARGB(255, 180, 134, 50),
    "topics": [
      {
        "number": 0,
        "title": "Introduction",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 1,
        "title": "Smartphone Usage",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 2,
        "title": "Online Shopping",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 3,
        "title": "Social Media Terms",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 4,
        "title": "Tech Support",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 5,
        "title": "Digital Banking",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 6,
        "title": "German Tech Brands",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
      {
        "number": 7,
        "title": "Chapter Quiz",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
    ]
  },
  {
    "number": 15,
    "level": "advanced",
    "image": "assets/home_screen/alphabets.png",
    "title": "Personal Growth",
    "color": Color.fromARGB(255, 102, 204, 255),
    "subColor": Color.fromARGB(255, 50, 134, 180),
    "topics": [
      {
        "number": 0,
        "title": "Introduction",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": true,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 1,
        "title": "Self-Improvement",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 2,
        "title": "Mental Health",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 3,
        "title": "Fitness & Wellness",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 4,
        "title": "Learning Strategies",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 5,
        "title": "Time Management",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 6,
        "title": "German Lifestyle Trends",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": false,
        "isPast": false,
      },
      {
        "number": 7,
        "title": "Chapter Quiz",
        "image": "assets/home_screen/alphabets.png",
        "isFirst": false,
        "isLast": true,
        "isPast": false,
      },
    ]
  }
];
